report_section_order:
  software_versions:
    order: -1000
  "goodwright-clipseq-summary":
    order: -1001

export_plots: true

# Run only these modules
run_modules:
  - custom_content
  - fastqc
  - cutadapt
  - bowtie
  - star

module_order:
  - fastqc:
      name: "FastQC (raw)"
      info: "This section of the report shows FastQC results before adapter trimming."
      path_filters:
        - "./fastqc/*.zip"
  - cutadapt
  - fastqc:
      name: "FastQC (trimmed)"
      info: "This section of the report shows FastQC results after adapter trimming."
      path_filters:
        - "./trimgalore/fastqc/*.zip"
  - bowtie
  - star
  - custom_content

custom_content:
  order:
    - software-versions-by-process
    - software-versions-unique

# Don't show % Dups in the General Stats table (we have this from Picard)
table_columns_visible:
  fastqc:
    percent_duplicates: False

# extra_fn_clean_trim:
#   - ".spikein"
#   - ".target"
#   - ".target.filtered"
#   - "_1"
#   - "_2"
#   - "_1_val_1"
#   - "_2_val_2"

# Customise the module search patterns to speed up execution time
sp:
  cutadapt:
    fn: "*trimming_report.txt"
  samtools/stats:
    fn: "*.stats"
  samtools/flagstat:
    fn: "*.flagstat"
  samtools/idxstats:
    fn: "*.idxstats*"

