name: pipeline CI
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  small_pipeline_test:
    name: Small pipeline test
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'goodwright/differential-analysis') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "22.10.1"
          - ""
        # profile: ["docker", "singularity"]
        profile: ["docker"]
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,${{ matrix.profile }} --outdir ./results

  nf_test:
    name: nf-test tests
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'goodwright/differential-analysis') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "22.10.1"
          - ""
        profile: ["docker"]
        test:
          - "comparison_none"
          - "comparison_single"
          - "comparison_multi"
          - "multi_count"
          - "gsea"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        run: |
          wget -qO- https://github.com/askimed/nf-test/releases/download/v0.7.1/nf-test-0.7.1.tar.gz | tar -xz
          APP_HOME=${HOME}/.nf-test
          mkdir -p ${APP_HOME}
          mv -f nf-test.jar ${APP_HOME}/nf-test.jar
          mv nf-test /usr/local/bin/

      - name: Run nf-test
        run: |
          nf-test test \
            --profile=test,${{ matrix.profile }} \
            tests/nftest/${{ matrix.test }}.nf.test \
            --tap=test.tap

      - uses: pcolby/tap-summary@v1
        with:
          path: >-
            test.tap
